export const CLASSES = {
    container:       'wizard-container',
    perguntaDestaque:'pergunta-destaque',
    alerta:          'alerta',
    listaOpcoes:     'opcoes-lista',
    linkExterno:     'acao-externa',
    srOnly:          'sr-only',
    campoFormulario: 'campo-formulario',
    campoOpcional:   'campo-opcional',
    campoInvalido:   'campo-invalido',
    radioOptions:    'radio-options',
    radioOption:     'radio-option',
    fileInfo:        'file-info',
    fileList:        'file-list',
    botaoSubmit:     'botao-submit',
    wizardForm:      'wizard-form',
};